services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movieclub
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '8092:3000'
    volumes:
      - ./:/app/data
    environment:
      DATABASE_URL: file:/app/data/movieclub.db
